# NON GRADED CHALLENGE 8

## Carilah GRADIENT dari sebuah fungsi berikut : 3x + 4y = 5

In [27]:
import numpy as np
from numpy import array

import sympy as sy
from sympy import symbols

import matplotlib.pyplot as plt

### Gradient sumbu X

In [22]:
x,y = symbols('x y')

In [23]:
# Mengisi sumbu x

x = np.linspace(-10, 10)

In [24]:
# 3*x + 4*y = 5
# y = 5/4 - 3/4*x
y = 1.25 - 0.75 * x
y

array([ 8.75      ,  8.44387755,  8.1377551 ,  7.83163265,  7.5255102 ,
        7.21938776,  6.91326531,  6.60714286,  6.30102041,  5.99489796,
        5.68877551,  5.38265306,  5.07653061,  4.77040816,  4.46428571,
        4.15816327,  3.85204082,  3.54591837,  3.23979592,  2.93367347,
        2.62755102,  2.32142857,  2.01530612,  1.70918367,  1.40306122,
        1.09693878,  0.79081633,  0.48469388,  0.17857143, -0.12755102,
       -0.43367347, -0.73979592, -1.04591837, -1.35204082, -1.65816327,
       -1.96428571, -2.27040816, -2.57653061, -2.88265306, -3.18877551,
       -3.49489796, -3.80102041, -4.10714286, -4.41326531, -4.71938776,
       -5.0255102 , -5.33163265, -5.6377551 , -5.94387755, -6.25      ])

In [25]:
gradient_x = np.gradient(y)
gradient_x

array([-0.30612245, -0.30612245, -0.30612245, -0.30612245, -0.30612245,
       -0.30612245, -0.30612245, -0.30612245, -0.30612245, -0.30612245,
       -0.30612245, -0.30612245, -0.30612245, -0.30612245, -0.30612245,
       -0.30612245, -0.30612245, -0.30612245, -0.30612245, -0.30612245,
       -0.30612245, -0.30612245, -0.30612245, -0.30612245, -0.30612245,
       -0.30612245, -0.30612245, -0.30612245, -0.30612245, -0.30612245,
       -0.30612245, -0.30612245, -0.30612245, -0.30612245, -0.30612245,
       -0.30612245, -0.30612245, -0.30612245, -0.30612245, -0.30612245,
       -0.30612245, -0.30612245, -0.30612245, -0.30612245, -0.30612245,
       -0.30612245, -0.30612245, -0.30612245, -0.30612245, -0.30612245])

### Gradient sumbu Y

In [26]:
x,y = symbols('x y')

In [28]:
# Mengisi sumbu y

y = np.linspace(-10, 10)

In [29]:
# 3*x + 4*y = 5
x = (5/3) + (4/3)*y
x

array([-11.66666667, -11.12244898, -10.57823129, -10.03401361,
        -9.48979592,  -8.94557823,  -8.40136054,  -7.85714286,
        -7.31292517,  -6.76870748,  -6.2244898 ,  -5.68027211,
        -5.13605442,  -4.59183673,  -4.04761905,  -3.50340136,
        -2.95918367,  -2.41496599,  -1.8707483 ,  -1.32653061,
        -0.78231293,  -0.23809524,   0.30612245,   0.85034014,
         1.39455782,   1.93877551,   2.4829932 ,   3.02721088,
         3.57142857,   4.11564626,   4.65986395,   5.20408163,
         5.74829932,   6.29251701,   6.83673469,   7.38095238,
         7.92517007,   8.46938776,   9.01360544,   9.55782313,
        10.10204082,  10.6462585 ,  11.19047619,  11.73469388,
        12.27891156,  12.82312925,  13.36734694,  13.91156463,
        14.45578231,  15.        ])

In [30]:
gradient_y = np.gradient(x)
gradient_y

array([0.54421769, 0.54421769, 0.54421769, 0.54421769, 0.54421769,
       0.54421769, 0.54421769, 0.54421769, 0.54421769, 0.54421769,
       0.54421769, 0.54421769, 0.54421769, 0.54421769, 0.54421769,
       0.54421769, 0.54421769, 0.54421769, 0.54421769, 0.54421769,
       0.54421769, 0.54421769, 0.54421769, 0.54421769, 0.54421769,
       0.54421769, 0.54421769, 0.54421769, 0.54421769, 0.54421769,
       0.54421769, 0.54421769, 0.54421769, 0.54421769, 0.54421769,
       0.54421769, 0.54421769, 0.54421769, 0.54421769, 0.54421769,
       0.54421769, 0.54421769, 0.54421769, 0.54421769, 0.54421769,
       0.54421769, 0.54421769, 0.54421769, 0.54421769, 0.54421769])